# Generated by Django 5.0 on 2025-01-07 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_initial'),
    ]

    operations = [
    ]
