# Generated by Django 5.0 on 2025-01-07 01:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_auto_20250107_0200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_lessons',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='earned_at',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='points_required',
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(default='Achievement Description'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='New Achievement', max_length=100),
        ),
        migrations.AddField(
            model_name='achievement',
            name='points_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='badge',
            name='required_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(upload_to='badges/'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('action', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
